package fr.vbrosseau.freshrssdiscover.data.security

import android.util.Base64
import timber.log.Timber
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES/GCM encryption of secrets written to disk.
 *
 * The key comes from [SecretKeySource] and is not created here: that split is
 * what makes this class testable. The hardware keystore stays out of reach of
 * tests — see [SecretKeySource].
 *
 * GCM rather than CBC: the mode authenticates the message as well as
 * encrypting it. A modified byte in the preferences file fails decryption
 * instead of yielding a near-miss text the application would take for a token.
 */
@Singleton
internal class KeystoreSecretCipher @Inject constructor(
    private val keys: SecretKeySource,
) : SecretCipher {
    override fun encrypt(plainText: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, keys.key())

        // The initialization vector is generated by the cipher and must
        // accompany the message: without it, decryption is impossible. It is
        // not secret.
        val encrypted = cipher.doFinal(plainText.toByteArray())
        return encode(cipher.iv) + SEPARATOR + encode(encrypted)
    }

    override fun decrypt(cipherText: String): String? = runCatching {
        val (iv, payload) = cipherText.split(SEPARATOR).let { it[0] to it[1] }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, keys.key(), GCMParameterSpec(TAG_LENGTH_BITS, decode(iv)))
        String(cipher.doFinal(decode(payload)))
    }.getOrElse { failure ->
        // Real-world case: the user changed their screen lock, or restored a
        // backup on another device. The key is lost, the secret unreadable —
        // the session must be treated as absent.
        Timber.w("Secret illisible, session considérée absente : %s", failure.javaClass.simpleName)
        null
    }

    private fun encode(bytes: ByteArray): String = Base64.encodeToString(bytes, Base64.NO_WRAP)

    private fun decode(text: String): ByteArray = Base64.decode(text, Base64.NO_WRAP)

    private companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val TAG_LENGTH_BITS = 128
        const val SEPARATOR = ":"
    }
}
