package fr.vbrosseau.freshrssdiscover.presentation.settings

/** Test tags for the settings screen. */
object SettingsTestTags {
    const val SERVER_ADDRESS = "settings:server"
    const val USERNAME = "settings:username"
    const val NO_SESSION = "settings:no-session"
    const val FEEDS = "settings:feeds"
    const val PRESENTATION_LIST = "settings:presentation-list"
    const val PRESENTATION_IMMERSIVE = "settings:presentation-immersive"
    const val PRESENTATION_DESCRIPTION = "settings:presentation-description"
    const val AUTO_MARK_AS_READ = "settings:auto-mark-as-read"
    const val AUTO_MARK_AS_READ_HELP = "settings:auto-mark-as-read-help"
    const val VISIBLE_FRACTION = "settings:visible-fraction"
    const val VISIBLE_FRACTION_SLIDER = "settings:visible-fraction-slider"
    const val CONTINUOUS_VISIBILITY = "settings:continuous-visibility"
    const val CONTINUOUS_VISIBILITY_SLIDER = "settings:continuous-visibility-slider"
    const val REMINDER = "settings:reminder"
    const val REMINDER_HELP = "settings:reminder-help"
    const val REMINDER_FIXED_HOUR = "settings:reminder-fixed-hour"
    const val REMINDER_FIXED_HOUR_HELP = "settings:reminder-fixed-hour-help"
    const val REMINDER_HOUR_VALUE = "settings:reminder-hour-value"
    const val REMINDER_HOUR_DIALOG = "settings:reminder-hour-dialog"
    const val REMINDER_HOUR_CONFIRM = "settings:reminder-hour-confirm"
    const val REMINDER_HOUR_CANCEL = "settings:reminder-hour-cancel"
    const val READING_STATS = "settings:reading-stats"
    const val CACHE_SIZE = "settings:cache-size"
    const val CACHE_PURGEABLE = "settings:cache-purgeable"
    const val PURGE_CACHE = "settings:purge-cache"
    const val CACHE_PURGE_RESULT = "settings:cache-purge-result"
    const val SIGN_OUT = "settings:sign-out"
    const val SIGN_OUT_DIALOG = "settings:sign-out-dialog"
    const val SIGN_OUT_CONFIRM = "settings:sign-out-confirm"
    const val SIGN_OUT_CANCEL = "settings:sign-out-cancel"
    const val APP_VERSION = "settings:version"
    const val LICENSE = "settings:license"
}
